multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: world
    child_frame_id: world
groups:
  - name: lwr_arm
    base_link: calib_lwr_arm_base_link
    tip_link: lwr_arm_7_link
default_collision_operations:
  - object1: world
    object2: world_link
    operation: disable  # Adjacent in collision
  - object1: world_link
    object2: calib_lwr_arm_base_link
    operation: disable  # Adjacent in collision
  - object1: calib_lwr_arm_base_link
    object2: lwr_arm_1_link
    operation: disable  # Adjacent in collision
  - object1: lwr_arm_1_link
    object2: lwr_arm_2_link
    operation: disable  # Adjacent in collision
  - object1: lwr_arm_2_link
    object2: lwr_arm_3_link
    operation: disable  # Adjacent in collision
  - object1: lwr_arm_3_link
    object2: lwr_arm_4_link
    operation: disable  # Adjacent in collision
  - object1: lwr_arm_4_link
    object2: lwr_arm_5_link
    operation: disable  # Adjacent in collision
  - object1: lwr_arm_5_link
    object2: lwr_arm_6_link
    operation: disable  # Adjacent in collision
  - object1: lwr_arm_6_link
    object2: lwr_arm_7_link
    operation: disable  # Adjacent in collision
  - object1: calib_lwr_arm_base_link
    object2: lwr_arm_2_link
    operation: disable  # Never in collision
  - object1: calib_lwr_arm_base_link
    object2: lwr_arm_3_link
    operation: disable  # Never in collision
  - object1: calib_lwr_arm_base_link
    object2: lwr_arm_4_link
    operation: disable  # Never in collision
  - object1: calib_lwr_arm_base_link
    object2: lwr_arm_6_link
    operation: disable  # Never in collision
  - object1: lwr_arm_1_link
    object2: lwr_arm_3_link
    operation: disable  # Never in collision
  - object1: lwr_arm_1_link
    object2: lwr_arm_4_link
    operation: disable  # Never in collision
  - object1: lwr_arm_1_link
    object2: lwr_arm_5_link
    operation: disable  # Never in collision
  - object1: lwr_arm_1_link
    object2: lwr_arm_6_link
    operation: disable  # Never in collision
  - object1: lwr_arm_1_link
    object2: world_link
    operation: disable  # Never in collision
  - object1: lwr_arm_2_link
    object2: lwr_arm_4_link
    operation: disable  # Never in collision
  - object1: lwr_arm_2_link
    object2: lwr_arm_5_link
    operation: disable  # Never in collision
  - object1: lwr_arm_2_link
    object2: lwr_arm_6_link
    operation: disable  # Never in collision
  - object1: lwr_arm_2_link
    object2: world_link
    operation: disable  # Never in collision
  - object1: lwr_arm_3_link
    object2: lwr_arm_5_link
    operation: disable  # Never in collision
  - object1: lwr_arm_3_link
    object2: lwr_arm_6_link
    operation: disable  # Never in collision
  - object1: lwr_arm_3_link
    object2: world_link
    operation: disable  # Never in collision
  - object1: lwr_arm_4_link
    object2: lwr_arm_6_link
    operation: disable  # Never in collision
  - object1: lwr_arm_4_link
    object2: world_link
    operation: disable  # Never in collision